config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :coordenadors, path: :coordenadores
  resources :offers do
    collection do
      patch :load_grid
      get :ptd_index, constraints: lambda { |req| req.format == :json }
      # get '/course_plans/:user_id', to: 'plans#course_plans'
      # patch :load_grid_disciplines
    end
    member do
      post :gerar_planos_lote
    end
    resources :offer_disciplines do
      resources :plans do
        member do
          get 'copy'
          get 'copy_outra_oferta'
          post 'aprovar'
          get 'enviar_aviso_nupe'
        end
      end
    end
  end

  get "planos/:id/parecer" => 'plans#plano_parecer', :as => :plano_parecer
  get 'planos/:course_id', to: 'plans#planos_curso', as: 'planos_curso'
  get 'planos', to: 'plans#planos_professor', as: 'planos_professor'
  # put 'update_perfils/:users', to: 'user#update_perfils', as: 'update_perfils_users'
  get 'aprovacao', to: 'plans#get_planos_aprovar', as: 'get_planos_aprovar'
  # get 'aprovacao_user', to: 'plans#get_planos_user_aprovar', as: 'get_planos_user_aprovar'
  # put 'aprovacao/:plan', to: 'plans#aprovar', as: 'aprovar_plano'

  # Área pública para planos
  get 'plans/public/index', to: 'plans#public_index', as: 'public_index'
  post 'plans/public/index', to: 'plans#public_index_course', as: 'public_index_course'

  get 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplinas', as: 'public_disciplinas'
  post 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplina_planos', as: 'public_disciplina_planos'

  get 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'
  # post 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'

  get 'plans/publico/index', to: 'plans#publico_index', as: 'publico_index'
  post 'plans/publico/index', to: 'plans#publico_index_planos', as: 'publico_index_planos'
  get 'plans/admin/enviar_aviso_nupe', to: 'plans#enviar_aviso_nupe', as: 'admin_enviar_aviso_nupe'
  match '/pesquisar' => 'plans#pesquisar', as: 'pesquisar_planos', via: [:get, :post]

  # Coordenação de curso
  match '/ofertas_coordenador' => 'offers#pesquisar', as: 'ofertas_coordenador', via: [:get, :post]
  match '/ofertas_coordenador/enviar_aviso_plano_pendente' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_plano_pendente', via: [:get]
  match '/ofertas_coordenador/enviar_aviso_planos_pendentes' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_planos_pendentes', via: [:get]

  resources :grid_disciplines
  resources :grids, except: [:destroy] do
    member do
      get 'copy'
    end
    collection do
      get :importar
      post  :importar
    end
    resources :grid_disciplines
  end
  resources :turmas
  resources :course_offers
  resources :courses
  resources :course_modalities
  resources :course_formats
  resources :disciplines, path: 'disciplinas'
  resources :permissao_telas
  resources :permissaos
  resources :perfils
  resources :roles
  resources :perfil_roles, except: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Configurar para que a tela inicial seja a tela de login, caso não esteja autenticado
  devise_for :users, skip: [:sessions]
    as :user do
      get 'login', to: 'devise/sessions#new', as: :new_user_session
      post 'login', to: 'devise/sessions#create', as: :user_session
      match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end
  # unauthenticated do
  #   as :user do
  #     root to: 'devise/sessions#new'
  #   end
  # end

  resources :users do
    collection do
      put 'update_perfils'
    end
  end

  # Interface para acessar as tarefas em background através do sidekiq
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq' if Rails.env.production? #|| Rails.env.staging?
  end

  # endereço para ver os e-mails no ambiente de aprovação (staging)
  # mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.staging? || Rails.env.development?

  root to: 'visitors#index'

end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :grid
  # belongs_to :turma
  has_many :offer_disciplines, dependent: :destroy
  accepts_nested_attributes_for :offer_disciplines

  enum offer_types: {
    regular: 'Regular', domiciliar: 'Exercício domiciliar', distancia: 'Atividades Não Presenciais',
    reoferta: 'Reoferta', dependencia: 'Dependência'
  }

  validates :type_offer, :grid_id, presence:true
  validates :semestre, presence: { if: -> { self.grid.course.course_offer.description.eql?("semestral") } }

  validates :year, presence: { if: -> { semestre.blank? } },
    format: {
      with: /(19|20)\d{2}/i
    },
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1900,
      less_than_or_equal_to: Date.today.year + 25
    }

  validates :offer_disciplines, presence:true#, on: [:update]
  
  validates :grid_id,
    uniqueness: {
      scope: [:turma, :year, :semestre, :grid_id, :type_offer],
      conditions: -> { where(active: true) },
      message: lambda { |x, y| "Já existe grade ofertada para esta turma, ano e semestre." }
    }
  
    # validates :turma, :dtprevisao_entrega_plano, presence:false
  validates :dtprevisao_entrega_plano, date: { if: -> { !dtprevisao_entrega_plano.blank? } }

  # accepts_nested_attributes_for :grid_disciplines, :allow_destroy => true

  def decorate
    @decorate ||= OfferDecorator.new self
  end

  attr_accessor :grid_year, :grid_semestre

  def attributes
    super.merge(
      'grid_year' => self.grid_year,
      'grid_semestre' => self.grid_semestre,
      'offer_disciplines' => self.offer_disciplines.build
    )
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  include PlansHelper

  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :ptd_index]
  load_and_authorize_resource :except => [:index, :show, :ptd_index]
  responders :flash

  # add_breadcrumb (I18n.t "helpers.links.pages.#{controller_name}", default: controller_name), :offers_path, :except => %w(pesquisar)

  before_action :load_cursos
  before_action :load_professores
  before_action :load_grades

  # GET /offers
  # GET /offers.json
  def index    
    # @offers = Offer.all
    respond_to do |format|
      format.html
      format.json { 
        if params[:draw]
          render json: OfferDatatable.new(view_context) 
        else
          @ofertas = Offer.all.includes(:offer_disciplines => :grid_discipline)
          render :partial => "offers/ofertas.json"
          # render json: Offer.all.includes(:offer_disciplines => :grid_discipline)
        end
      }
    end
  end

  # Exemplo: http://localhost:3000/offers/ptd_index.json?year=2018
  def ptd_index
    year = params[:year]
    semestre = params[:semestre]

    if year.nil?
      @ofertas = Offer.all
    else
      if !year.nil? && !semestre.nil?
        @ofertas = Offer.where(year: params[:year].to_i, semestre: params[:semestre].to_i)
      else
        @ofertas = Offer.where(year: params[:year].to_i)
      end
    end

    @ofertas.includes(:offer_disciplines => :grid_discipline)
    render :partial => "offers/ofertas.json"
  end
  

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
    params[:grid_id] = @offer.grid_id
    params[:grid_year] = @offer.year_base
    params[:grid_semestre] = @offer.semestre_base
    # parâmetro utilizado para mostrar ou não o segundo professor ao editar
    params[:has_second_user] = @offer.offer_disciplines.where.not(second_user:nil).count > 0

    @grade_anos = load_grade_anos(params[:grid_id])
    @grade_semestres = load_grade_semestres(params[:grid_id])
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.grid_id = params[:grid_id]
    @offer.year_base = params[:grid_year]
    @offer.semestre_base = params[:grid_semestre]

    @grade_anos = load_grade_anos(params[:grid_id])
    @grade_semestres = load_grade_semestres(params[:grid_id])

    respond_to do |format|
      if @offer.valid? && @offer.save
        format.html { redirect_to @offer, notice: t('flash.actions.create.notice', resource_name: controller_name.classify.constantize.model_name.human) }
        format.json { render :show, status: :created, location: @offer }
      elsif @offer.offer_disciplines.empty?
        @grid_disciplines = carregar_disciplinas_grade
        @offer.offer_disciplines = []
        @grid_disciplines.each do |g|
          @offer.offer_disciplines << OfferDiscipline.new(grid_discipline: g, user:nil)
        end
        format.html { render :new }
      else
        @grid_disciplines = carregar_disciplinas_grade
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    begin
      # @offer = Offer.new(offer_params)
      @offer.grid_id = params[:grid_id]
      @offer.year_base = params[:grid_year]
      @offer.semestre_base = params[:grid_semestre]
      
      @grade_anos = load_grade_anos(params[:grid_id])
      @grade_semestres = load_grade_semestres(params[:grid_id])

      respond_to do |format|
        if offer_params[:offer_disciplines_attributes].nil? || offer_params[:offer_disciplines_attributes].empty?
          @grid_disciplines = carregar_disciplinas_grade
          @offer.offer_disciplines = []
          @grid_disciplines.each do |g|
            @offer.offer_disciplines << OfferDiscipline.new(grid_discipline: g, user:nil)
          end
          format.html { render :edit }
        else
          ActiveRecord::Base.transaction do
            # offer_params[:offer_disciplines_attributes]
            if @offer.update(offer_params)
              # @offer.offer_disciplines.each do |d|
              #   offer_params[:offer_disciplines_attributes].each do |k,v|
              #     if !v[:id].empty? && v[:id].to_i == d.id
              #       OfferDisciplineTurma.where(offer_discipline_id: d.id).destroy_all
              #       v[:turmas_id].each do |turma|
              #         if !turma.empty?
              #           OfferDisciplineTurma.find_or_create_by!(offer_discipline_id: d.id, turma_id: turma.to_i)
              #         end
              #       end
              #     end
              #   end
              # end
              format.html { redirect_to @offer, notice: t('flash.actions.update.notice', resource_name: controller_name.classify.constantize.model_name.human) }
              format.json { render :show, status: :ok, location: @offer }
            else
              @grid_disciplines = carregar_disciplinas_grade
              format.html { render :edit }
              format.json { render json: @offer.errors, status: :unprocessable_entity }
            end
          end
        end

      end
    rescue ActiveRecord::InvalidForeignKey
      respond_to do |format|
        @grid_disciplines = carregar_disciplinas_grade
        flash[:alert] = 'Não é possível alterar a grade ofertada. Já existem planos gerados.'
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
    # salvar_atualizar(false)
    # respond_to do |format|
    #   if @offer.update(offer_params)
    #     format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @offer }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @offer.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: t('flash.actions.destroy.notice', resource_name: controller_name.classify.constantize.model_name.human) }
      format.json { head :no_content }
    end
  end

  def load_grid
    if !params[:grid_id].nil? && !params[:grid_id].blank?
      params[:tipo_oferta] = Grid.find(params[:grid_id]).course.course_offer.description

      if params[:grid_year].nil? && params[:grid_semestre].nil?
        @grade_anos = load_grade_anos(params[:grid_id])
        @grade_semestres = load_grade_semestres(params[:grid_id])
      else
        carregar_disciplinas_grade
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def pesquisar
    # @cursos_coordenador = Coordenador.where(user: current_user).pluck(:course_id) if !current_user.admin?
    # @cursos_coordenador = Offer.joins(:grid => :course).pluck('courses.id') if current_user.admin?

    # Se o usuário for um coordenador então mostra apenas os seus cursos
    if Coordenador.find_by(user: current_user).nil?
      @cursos_coordenador = Offer.joins(:grid => :course).pluck('courses.id')
    else
      @cursos_coordenador = Coordenador.where(user: current_user).pluck(:course_id)
    end
    if !@cursos_coordenador.empty?

      @ofertas = Offer.joins(:grid).where(:grids => { course_id: @cursos_coordenador})
      @turmas = @ofertas.order(turma: :desc).pluck(:turma).uniq
      @anos = @ofertas.order(year: :desc).pluck(:year).uniq
      @semestres = @ofertas.where.not(semestre: nil).order(semestre: :desc).pluck(:semestre).uniq
      # @semestres = [1,2]
      @cursos = Course.where(id: @cursos_coordenador)

      params[:curso] = @cursos.last.id if params[:curso].nil?
      params[:ano] = Date.today.year if params[:ano].nil?
      # params[:turma] = Date.today.year if params[:turma].nil?

      if !params[:curso].nil? && !params[:curso].blank?
        if !params[:ano].blank? && !params[:semestre].blank? && !params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.year = ? AND offers.semestre = ? and offers.turma = ?',
            params[:curso], params[:ano].to_i, params[:semestre].to_i, params[:turma].to_s
          ).order(semestre: :desc)
        elsif !params[:ano].blank? && params[:semestre].blank? && params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.year = ?',
            params[:curso], params[:ano].to_i
          ).order(semestre: :desc)
        elsif params[:ano].blank? && !params[:semestre].blank? && params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.semestre = ?',
            params[:curso], params[:semestre].to_i
          ).order(semestre: :desc)

        elsif !params[:ano].blank? && params[:semestre].blank? && !params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.year = ? AND offers.turma = ?',
            params[:curso], params[:ano].to_i, params[:turma].to_s
          ).order(semestre: :desc)

        elsif params[:ano].blank? && !params[:semestre].blank? && !params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.semestre = ? AND offers.turma = ?',
            params[:curso], params[:semestre].to_i, params[:turma].to_s
          ).order(semestre: :desc)

        elsif params[:ano].blank? && params[:semestre].blank? && !params[:turma].blank?

app/views/offers/coordenador/_form.html.erb
<%= form_with(url: ofertas_coordenador_path, local:true, method: :post) do |f| %>

  <div class="form-group">
    <%= label_tag :curso, '* Curso' %>
    <%= select_tag :curso, options_from_collection_for_select(@cursos, "id", "name", params[:curso]), id: :curso, class: 'form-control', prompt:'Selecione o curso', required:true, autofocus:true %>
  </div>

  <div class="form-group">
    <%= label_tag :turma, 'Turma' %>
    <%= select_tag :turma, options_for_select(@turmas, params[:turma]), id: :turma, class: 'form-control', prompt:'Turma' %>
  </div>

  <div class="form-group">
    <%= label_tag :ano, 'Ano da oferta' %>
    <%= select_tag :ano, options_for_select(@anos, params[:ano]), id: :ano, class: 'form-control', prompt:'Ano' %>
  </div>

  <div class="form-group">
    <%= label_tag :semestre, 'Semestre da oferta' %>
    <%= select_tag :semestre, options_for_select(@semestres, params[:semestre]), id: :semestre, class: 'form-control', prompt:'Semestre' %>
  </div>


  <!-- <div class="form-group col-md-12">
    <= f.check_box :analise, id: :plan_analise %>
    <= f.label :analise %>
    <= f.check_box :aprovado, id: :plan_aprovado %>
    <= f.label :aprovado %>
    <= f.check_box :reprovado, id: :plan_reprovado %>
    <= f.label :reprovado %>
  </div> -->

  <div class="form-group">
    <%= f.submit 'Pesquisar', class: 'btn btn-search btn-sm btn-block btn-primary' %>
  </div>
<% end if !cursos_coordenador.empty? %>

app/views/offers/coordenador/_resultado.html.erb
<% if resultado.nil? || resultado.empty? %>
  <p class="alert alert-warning">Nenhum plano de ensino encontrado com os parâmetros informados.</p>
<% else %>
  <% resultado.each do |oferta| %>
    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">
          <strong><%= oferta.grid.course.name %></strong>
          <span class="pull-right">
            <%= link_to gerar_planos_lote_offer_path(oferta, format: :pdf), method: :post, class: "btn btn-primary btn-xs" do %>
              <i class="fa fa-gear"></i>
              Gerar todos os planos
            <% end %>
            <%= link_to coor_enviar_aviso_planos_pendentes_path(offer_id: oferta), class: "btn btn-warning btn-xs", remote:true, id: "avisar_professores_#{oferta.id}" do %>
              <i class="fa fa-send"></i>
              <span title="Apenas para componente curricular pendente">Avisar professores</span>
            <% end %>
          </span>
        </h3>
        <small class="badge"><%= "Turma: #{oferta.turma}" %></small>
        <small class="badge"><%= "Ano/Semestre: #{oferta.decorate.ano_semestre}" %></small>
      </div>
      <div class="panel-body">
        <table class='table table-striped table-bordered table-condensed'>
          <thead class="alert alert-info">
            <tr>
              <th>Componente curricular</th>
              <th>Professor</th>
              <th class="text-center">Situação do plano</th>
              <th class="text-center">Detalhes</th>
              <th class="text-center">PDF</th>
              <th class="text-center">Aviso</th>
            </tr>
          </thead>
          <tbody>
              <% oferta.offer_disciplines.each do |od| %>
                <% if ['reoferta', 'dependencia'].include?(oferta.type_offer) %>
                  <% if !od.user.nil? || !od.second_user.nil? %>
                    <%= render 'offers/coordenador/resultado_item', od: od %>
                  <% end %>
                <% else %>
                  <%= render 'offers/coordenador/resultado_item', od: od %>
                <% end %>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
<% end %>

app/views/offers/coordenador/_resultado_item.html.erb
<% plano = od.plans.order(versao: :desc).first unless od.plans.empty? %>
<tr>
  <td><%= od.grid_discipline.discipline.decorate.title %></td>
  <% if od.user.nil? %>
    <td><span class="label label-danger label-block" style="font-size: 14px;">Não possui</span></td>
  <% else %>
    <td><%= od.user.name %></td>
  <% end %>
  <% if plano.nil? %>
    <td><span class="label label-danger label-block" style="font-size: 14px;">Não possui</span></td>
  <% else %>
    <td><%= plano.decorate.situacao 'label-block' %></td>
  <% end %>

  <% if !plano.nil? %>
    <td><%= plano.decorate.link_show 'btn-xs btn-block' %></td>
    <td><%= plano.decorate.link_pdf 'btn-xs btn-block' %></td>
  <% else %>
    <td class="well"></td>
    <td class="well"></td>
  <% end %>
  <% if !od.user.nil? && (plano.nil? || (!plano.nil? && !plano.user.nil? && !plano.aprovado? && (!plano.analise? || plano.reprovado?))) %>
    <td>
      <%= link_to coor_enviar_aviso_plano_pendente_path(offer_discipline_id: od), class: "btn btn-warning btn-xs btn-block",
          remote:true, id: "avisar_professor_#{od.id}" do %>
          <i class="fa fa-send"></i>
          Avisar professor
      <% end %>
    </td>
  <% else %>
  <td class="well"></td>
  <% end %>
</tr>

app/views/offers/coordenador/index.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Filtros</h3>
      </div>
      <div class="panel-body">
        <%= render 'offers/coordenador/form', cursos_coordenador: @cursos_coordenador %>
      </div>
    </div>
  </div>

  <div class="col-md-9" id="resultado">
    <%= render 'offers/coordenador/resultado', resultado: @resultado %>
  </div>
</div>