config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :coordenadors, path: :coordenadores
  resources :offers do
    collection do
      patch :load_grid
      get :ptd_index, constraints: lambda { |req| req.format == :json }
      # get '/course_plans/:user_id', to: 'plans#course_plans'
      # patch :load_grid_disciplines
    end
    member do
      post :gerar_planos_lote
    end
    resources :offer_disciplines do
      resources :plans do
        member do
          get 'copy'
          get 'copy_outra_oferta'
          post 'aprovar'
          get 'enviar_aviso_nupe'
        end
      end
    end
  end

  get "planos/:id/parecer" => 'plans#plano_parecer', :as => :plano_parecer
  get 'planos/:course_id', to: 'plans#planos_curso', as: 'planos_curso'
  get 'planos', to: 'plans#planos_professor', as: 'planos_professor'
  # put 'update_perfils/:users', to: 'user#update_perfils', as: 'update_perfils_users'
  get 'aprovacao', to: 'plans#get_planos_aprovar', as: 'get_planos_aprovar'
  # get 'aprovacao_user', to: 'plans#get_planos_user_aprovar', as: 'get_planos_user_aprovar'
  # put 'aprovacao/:plan', to: 'plans#aprovar', as: 'aprovar_plano'

  # Área pública para planos
  get 'plans/public/index', to: 'plans#public_index', as: 'public_index'
  post 'plans/public/index', to: 'plans#public_index_course', as: 'public_index_course'

  get 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplinas', as: 'public_disciplinas'
  post 'plans/public/:course_id/disciplinas', to: 'plans#public_disciplina_planos', as: 'public_disciplina_planos'

  get 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'
  # post 'plans/public/:course_id/:discipline_id/planos', to: 'plans#public_curso_disciplina_planos', as: 'public_curso_disciplina_planos'

  get 'plans/publico/index', to: 'plans#publico_index', as: 'publico_index'
  post 'plans/publico/index', to: 'plans#publico_index_planos', as: 'publico_index_planos'
  get 'plans/admin/enviar_aviso_nupe', to: 'plans#enviar_aviso_nupe', as: 'admin_enviar_aviso_nupe'
  match '/pesquisar' => 'plans#pesquisar', as: 'pesquisar_planos', via: [:get, :post]

  # Coordenação de curso
  match '/ofertas_coordenador' => 'offers#pesquisar', as: 'ofertas_coordenador', via: [:get, :post]
  match '/ofertas_coordenador/enviar_aviso_plano_pendente' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_plano_pendente', via: [:get]
  match '/ofertas_coordenador/enviar_aviso_planos_pendentes' => 'offers#enviar_aviso_plano_pendente', as: 'coor_enviar_aviso_planos_pendentes', via: [:get]

  resources :grid_disciplines
  resources :grids, except: [:destroy] do
    member do
      get 'copy'
    end
    collection do
      get :importar
      post  :importar
    end
    resources :grid_disciplines
  end
  resources :turmas
  resources :course_offers
  resources :courses
  resources :course_modalities
  resources :course_formats
  resources :disciplines, path: 'disciplinas'
  resources :permissao_telas
  resources :permissaos
  resources :perfils
  resources :roles
  resources :perfil_roles, except: [:show]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Configurar para que a tela inicial seja a tela de login, caso não esteja autenticado
  devise_for :users, skip: [:sessions]
    as :user do
      get 'login', to: 'devise/sessions#new', as: :new_user_session
      post 'login', to: 'devise/sessions#create', as: :user_session
      match 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via
  end
  # unauthenticated do
  #   as :user do
  #     root to: 'devise/sessions#new'
  #   end
  # end

  resources :users do
    collection do
      put 'update_perfils'
    end
  end

  # Interface para acessar as tarefas em background através do sidekiq
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq' if Rails.env.production? #|| Rails.env.staging?
  end

  # endereço para ver os e-mails no ambiente de aprovação (staging)
  # mount LetterOpenerWeb::Engine, at: "/mails" if Rails.env.staging? || Rails.env.development?

  root to: 'visitors#index'

end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :grid
  # belongs_to :turma
  has_many :offer_disciplines, dependent: :destroy
  accepts_nested_attributes_for :offer_disciplines

  enum offer_types: {
    regular: 'Regular', domiciliar: 'Exercício domiciliar', distancia: 'Atividades Não Presenciais',
    reoferta: 'Reoferta', dependencia: 'Dependência'
  }

  validates :type_offer, :grid_id, presence:true
  validates :semestre, presence: { if: -> { self.grid.course.course_offer.description.eql?("semestral") } }

  validates :year, presence: { if: -> { semestre.blank? } },
    format: {
      with: /(19|20)\d{2}/i
    },
    numericality: {
      only_integer: true,
      greater_than_or_equal_to: 1900,
      less_than_or_equal_to: Date.today.year + 25
    }

  validates :offer_disciplines, presence:true#, on: [:update]
  
  validates :grid_id,
    uniqueness: {
      scope: [:turma, :year, :semestre, :grid_id, :type_offer],
      conditions: -> { where(active: true) },
      message: lambda { |x, y| "Já existe grade ofertada para esta turma, ano e semestre." }
    }
  
    # validates :turma, :dtprevisao_entrega_plano, presence:false
  validates :dtprevisao_entrega_plano, date: { if: -> { !dtprevisao_entrega_plano.blank? } }

  # accepts_nested_attributes_for :grid_disciplines, :allow_destroy => true

  def decorate
    @decorate ||= OfferDecorator.new self
  end

  attr_accessor :grid_year, :grid_semestre

  def attributes
    super.merge(
      'grid_year' => self.grid_year,
      'grid_semestre' => self.grid_semestre,
      'offer_disciplines' => self.offer_disciplines.build
    )
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  include PlansHelper

  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :ptd_index]
  load_and_authorize_resource :except => [:index, :show, :ptd_index]
  responders :flash

  # add_breadcrumb (I18n.t "helpers.links.pages.#{controller_name}", default: controller_name), :offers_path, :except => %w(pesquisar)

  before_action :load_cursos
  before_action :load_professores
  before_action :load_grades

  # GET /offers
  # GET /offers.json
  def index    
    # @offers = Offer.all
    respond_to do |format|
      format.html
      format.json { 
        if params[:draw]
          render json: OfferDatatable.new(view_context) 
        else
          @ofertas = Offer.all.includes(:offer_disciplines => :grid_discipline)
          render :partial => "offers/ofertas.json"
          # render json: Offer.all.includes(:offer_disciplines => :grid_discipline)
        end
      }
    end
  end

  # Exemplo: http://localhost:3000/offers/ptd_index.json?year=2018
  def ptd_index
    year = params[:year]
    semestre = params[:semestre]

    if year.nil?
      @ofertas = Offer.all
    else
      if !year.nil? && !semestre.nil?
        @ofertas = Offer.where(year: params[:year].to_i, semestre: params[:semestre].to_i)
      else
        @ofertas = Offer.where(year: params[:year].to_i)
      end
    end

    @ofertas.includes(:offer_disciplines => :grid_discipline)
    render :partial => "offers/ofertas.json"
  end
  

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
    params[:grid_id] = @offer.grid_id
    params[:grid_year] = @offer.year_base
    params[:grid_semestre] = @offer.semestre_base
    # parâmetro utilizado para mostrar ou não o segundo professor ao editar
    params[:has_second_user] = @offer.offer_disciplines.where.not(second_user:nil).count > 0

    @grade_anos = load_grade_anos(params[:grid_id])
    @grade_semestres = load_grade_semestres(params[:grid_id])
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)
    @offer.grid_id = params[:grid_id]
    @offer.year_base = params[:grid_year]
    @offer.semestre_base = params[:grid_semestre]

    @grade_anos = load_grade_anos(params[:grid_id])
    @grade_semestres = load_grade_semestres(params[:grid_id])

    respond_to do |format|
      if @offer.valid? && @offer.save
        format.html { redirect_to @offer, notice: t('flash.actions.create.notice', resource_name: controller_name.classify.constantize.model_name.human) }
        format.json { render :show, status: :created, location: @offer }
      elsif @offer.offer_disciplines.empty?
        @grid_disciplines = carregar_disciplinas_grade
        @offer.offer_disciplines = []
        @grid_disciplines.each do |g|
          @offer.offer_disciplines << OfferDiscipline.new(grid_discipline: g, user:nil)
        end
        format.html { render :new }
      else
        @grid_disciplines = carregar_disciplinas_grade
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    begin
      # @offer = Offer.new(offer_params)
      @offer.grid_id = params[:grid_id]
      @offer.year_base = params[:grid_year]
      @offer.semestre_base = params[:grid_semestre]
      
      @grade_anos = load_grade_anos(params[:grid_id])
      @grade_semestres = load_grade_semestres(params[:grid_id])

      respond_to do |format|
        if offer_params[:offer_disciplines_attributes].nil? || offer_params[:offer_disciplines_attributes].empty?
          @grid_disciplines = carregar_disciplinas_grade
          @offer.offer_disciplines = []
          @grid_disciplines.each do |g|
            @offer.offer_disciplines << OfferDiscipline.new(grid_discipline: g, user:nil)
          end
          format.html { render :edit }
        else
          ActiveRecord::Base.transaction do
            # offer_params[:offer_disciplines_attributes]
            if @offer.update(offer_params)
              # @offer.offer_disciplines.each do |d|
              #   offer_params[:offer_disciplines_attributes].each do |k,v|
              #     if !v[:id].empty? && v[:id].to_i == d.id
              #       OfferDisciplineTurma.where(offer_discipline_id: d.id).destroy_all
              #       v[:turmas_id].each do |turma|
              #         if !turma.empty?
              #           OfferDisciplineTurma.find_or_create_by!(offer_discipline_id: d.id, turma_id: turma.to_i)
              #         end
              #       end
              #     end
              #   end
              # end
              format.html { redirect_to @offer, notice: t('flash.actions.update.notice', resource_name: controller_name.classify.constantize.model_name.human) }
              format.json { render :show, status: :ok, location: @offer }
            else
              @grid_disciplines = carregar_disciplinas_grade
              format.html { render :edit }
              format.json { render json: @offer.errors, status: :unprocessable_entity }
            end
          end
        end

      end
    rescue ActiveRecord::InvalidForeignKey
      respond_to do |format|
        @grid_disciplines = carregar_disciplinas_grade
        flash[:alert] = 'Não é possível alterar a grade ofertada. Já existem planos gerados.'
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
    # salvar_atualizar(false)
    # respond_to do |format|
    #   if @offer.update(offer_params)
    #     format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @offer }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @offer.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: t('flash.actions.destroy.notice', resource_name: controller_name.classify.constantize.model_name.human) }
      format.json { head :no_content }
    end
  end

  def load_grid
    if !params[:grid_id].nil? && !params[:grid_id].blank?
      params[:tipo_oferta] = Grid.find(params[:grid_id]).course.course_offer.description

      if params[:grid_year].nil? && params[:grid_semestre].nil?
        @grade_anos = load_grade_anos(params[:grid_id])
        @grade_semestres = load_grade_semestres(params[:grid_id])
      else
        carregar_disciplinas_grade
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def pesquisar
    # @cursos_coordenador = Coordenador.where(user: current_user).pluck(:course_id) if !current_user.admin?
    # @cursos_coordenador = Offer.joins(:grid => :course).pluck('courses.id') if current_user.admin?

    # Se o usuário for um coordenador então mostra apenas os seus cursos
    if Coordenador.find_by(user: current_user).nil?
      @cursos_coordenador = Offer.joins(:grid => :course).pluck('courses.id')
    else
      @cursos_coordenador = Coordenador.where(user: current_user).pluck(:course_id)
    end
    if !@cursos_coordenador.empty?

      @ofertas = Offer.joins(:grid).where(:grids => { course_id: @cursos_coordenador})
      @turmas = @ofertas.order(turma: :desc).pluck(:turma).uniq
      @anos = @ofertas.order(year: :desc).pluck(:year).uniq
      @semestres = @ofertas.where.not(semestre: nil).order(semestre: :desc).pluck(:semestre).uniq
      # @semestres = [1,2]
      @cursos = Course.where(id: @cursos_coordenador)

      params[:curso] = @cursos.last.id if params[:curso].nil?
      params[:ano] = Date.today.year if params[:ano].nil?
      # params[:turma] = Date.today.year if params[:turma].nil?

      if !params[:curso].nil? && !params[:curso].blank?
        if !params[:ano].blank? && !params[:semestre].blank? && !params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.year = ? AND offers.semestre = ? and offers.turma = ?',
            params[:curso], params[:ano].to_i, params[:semestre].to_i, params[:turma].to_s
          ).order(semestre: :desc)
        elsif !params[:ano].blank? && params[:semestre].blank? && params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.year = ?',
            params[:curso], params[:ano].to_i
          ).order(semestre: :desc)
        elsif params[:ano].blank? && !params[:semestre].blank? && params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.semestre = ?',
            params[:curso], params[:semestre].to_i
          ).order(semestre: :desc)

        elsif !params[:ano].blank? && params[:semestre].blank? && !params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.year = ? AND offers.turma = ?',
            params[:curso], params[:ano].to_i, params[:turma].to_s
          ).order(semestre: :desc)

        elsif params[:ano].blank? && !params[:semestre].blank? && !params[:turma].blank?
          @resultado = Offer.joins(:grid).includes(:offer_disciplines => :plans).
          where('grids.course_id = ? AND offers.semestre = ? AND offers.turma = ?',
            params[:curso], params[:semestre].to_i, params[:turma].to_s
          ).order(semestre: :desc)

        elsif params[:ano].blank? && params[:semestre].blank? && !params[:turma].blank?

app/views/offers/_form.html.erb
<%= bootstrap_form_for(offer, local:true, label_errors: true, inline_errors: true, html: { class: "", role: "form" }) do |f| %>
  <%= error_messages_for(offer) %>
  <%= hidden_field_tag :grid_alterando, false %>

    <div class="row">
      <div class="form-group">
        <div class="form-group col-md-4">
          <%= f.label :grid_id %>
          <%= select_tag :grid_id, options_for_select(@grades.collect { |c| ["#{c.course.name} - #{c.year}", c.id ]}, params[:grid_id]),
            data: { remote: true, url: load_grid_offers_path, method: :patch },
            id: :grid_id, class: 'form-control', prompt:'Selecione a grade', required:true, autofocus:true %>
          <!-- <= select_tag :grid_id, options_for_select(@grades.collect { |c| ["#{c[4]} - #{c[3]} (Ano/semestre: #{c[1]}/#{c[2]})", "#{c[0]}" ]}, params[:grid_id]),
            data: { remote: true, url: load_grid_offers_path, method: :patch },
            id: :grid_id, class: 'form-control', prompt:'Selecione a grade', required:true %> -->
        </div>
        <div class="form-group col-md-2" id="grid_ano_semestre_partial">
          <%= render partial: 'grid_ano_semestre', locals: {} %>
        </div>
        <div class="form-group col-md-3">
          <%= f.text_field :dtprevisao_entrega_plano, 
              value: (@offer.dtprevisao_entrega_plano.strftime('%d/%m/%Y') unless @offer.dtprevisao_entrega_plano.nil?),
              :data => {:provider => 'datepicker'}, autocomplete: 'off' %>
        </div>
        <div class="form-group col-md-3">
          <%= f.label :active %>
          <%= f.check_box :active, id: :offer_active %>
        </div>
        
      </div>
    </div>

    <div class="row">

      <div class="col-md-3">
        <%= f.select :type_offer, Offer.offer_types.collect { |c| [c.last, c.first] }, {id: :type_offer, prompt: true} %>
      </div>
      <div class="col-md-3">
        <%= f.text_field :turma, id: :offer_turma, placeholder: 'Ex: 2018.A', label: "<span title='Ex: 2018.A'>Turma <i class='fa fa-info-circle'></i></span>".html_safe %>
        <!-- <= f.select :turma_id, Turma.where(active:true).collect { |c| ["#{c.year} - #{c.name}", c.id] },
          { prompt:true, id: :offer_turma_id },{ class: '' } %> -->
      </div>
      <div class="col-md-3">
        <%= f.number_field :year, id: :offer_year, placeholder:true %>
      </div>
      <div class="col-md-3">
        <% if !f.object.nil? && !f.object.grid.nil? && !f.object.grid.course.course_offer.description.eql?("semestral") %>
          <%= f.number_field :semestre, id: :offer_semestre, placeholder:'1,2,3...', disabled:true %>
        <% else %>
          <%= f.number_field :semestre, id: :offer_semestre, placeholder:'1,2,3...' %>
        <% end %>
      </div>

    </div>

  <div id="grid_disciplines_partial">
    <%= render partial: 'grid_disciplines_teacher', locals: {f: f, offer: offer} %>
  </div>

  <div class="fixed-on-bottom">
    <%= f.submit class: "btn btn-sm btn-primary" %>
  </div>

<% end %>

app/views/offers/_grid.html.erb
<div class="row">
  <% if @grid_disciplines %>
    <% grupos = @grid_disciplines.in_groups_of(5, false) %>

    <ul class="list-group">
      <li class="list-group-item list-group-item-success">Componentes curriculares da grade</li>
    </ul>
    <% grupos.each do |grupo| %>
      <div class="col-md-3">
        <ul class="list-group">
          <!-- <li class="list-group-item list-group-item-success">Componente curricular da grade</li> -->
          <% grupo.each do |g| %>
            <li class="list-group-item">
              <%= g.discipline.title %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <% else %>
    <div class="col-md-12">
      <div class="alert alert-warning" role="alert">
        Nenhuma componente curricular encontrado
      </div>
    </div>
  <% end %>

</div>

app/views/offers/edit.html.erb
<%- model = Offer %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= t('helpers.titles.edit', model: model.model_name.human.downcase) %>
    </h3>
  </div>
  <div class="panel-body">
    <%= render 'form', offer: @offer %>
  </div>
  <div class="panel-footer">
    <!-- <= link_to t('helpers.links.back'), discipline_path %> -->
    <%= link_to offers_path, class: 'btn btn-sm btn-default' do %>
      <i class='fa fa-list fa-2'></i>
      <%= t('helpers.links.back') %>
    <% end %>
    <%= link_to @offer, class: 'btn btn-sm btn-info' do %>
      <i class="fa fa-info fa-2" aria-hidden="true"></i>
      <%= t('helpers.links.show') %>
    <% end %>
  </div>
</div>

app/views/offers/enviar_aviso_plano_pendente.js.erb
// <= ajax_flash %>
$(".flash_messages").html('<%= j render partial: "layouts/messages", flash: flash %>');
$('#avisar_professores_<%= params[:offer_id] %>').attr('disabled','true');
$('#avisar_professor_<%= params[:offer_discipline_id] %>').attr('disabled','true');

app/views/offers/index.html.erb
<%- model = Offer %>

<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left">
      <%= link_to new_offer_path do %>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <%= t '.title', :default => model.model_name.human.pluralize.titleize %>
      <% end %>
    </h3>
    <div class="pull-right">

    </div>
  </div>
  <div class="panel-body">
    <div class="table-responsive">
      <%= content_tag :table, id: "offers_datatable", class: 'table table-striped table-bordered', role: :datatable, data: { url: offers_path(format: :json)} do %>
        <thead>
          <tr>
            <th><%= model.human_attribute_name(:year) %></th>
            <th><%= model.human_attribute_name(:semestre) %></th>
            <th><%= model.human_attribute_name(:type) %></th>
            <th><%= model.human_attribute_name(:course) %></th>
            <th><%= model.human_attribute_name(:turma) %></th>
            <!-- <th><= "Componente curriculars"</th> > -->
            <th><%= model.human_attribute_name(:active) %></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody></tbody>
      <% end %>
    </div>
  </div>
  <div class="panel-footer clearfix">
    <div class="">
      <%= link_to new_offer_path do %>
        <i class="fa fa-plus" aria-hidden="true"></i>
        <%= t('.new', :default => t("helpers.titles.new", model: model.model_name.human.downcase )) %>
      <% end %>
    </div>
    <div class="pull-right">

    </div>
  </div>
</div>

app/views/offers/show.html.erb
<%- model = Offer %>
<%- modelOfferDiscipline = OfferDiscipline %>
<%- modelGrid = Grid %>
<%- modelGridDiscipline = GridDiscipline %>
<%- modelCourse = Course %>
<%- modelDiscipline = Discipline %>

<!-- <div class="well well-sm">

</div> -->

<div class="panel panel-default">
  <div class="panel-heading">
      <!-- <= link_to offers_path, class: 'btn btn-xs btn-default pull-left' do %>
        <i class='fa fa-list fa-2'></i>
        <= t('helpers.links.back') %>
      < end %>
      <= link_to edit_offer_path(@offer), class: 'btn btn-xs btn-primary pull-left' do %>
        <i class='fa fa-pencil-square-o fa-2'></i>
        <= t('helpers.links.edit') %>
      < end %> -->
      <h3 class="panel-title">Detalhes da oferta</h3>
  </div>
  <div class="panel-body">

    <div class="col-md-offset-1 col-md-5 col-lg-offset-0 col-lg-6">

      <ul class="list-group">
        <li class="list-group-item list-group-item-success">
          Detalhes da oferta
        </li>
        <li class="list-group-item">
          Ano/Semestre
          <span class="badge"><%= @offer.decorate.ano_semestre %></span>
        </li>

        <li class="list-group-item">
          <%= model.human_attribute_name(:turma) %>
          <span class="badge"><%= "#{@offer.turma}" %></span>
        </li>

        <li class="list-group-item">
          <%= model.human_attribute_name(:type_offer) %>
          <span class="badge"><%= @offer.decorate.type_offer %></span>
        </li>
        
        <li class="list-group-item">
          <%= model.human_attribute_name(:dtprevisao_entrega_plano) %>
          <span class="badge"><%= @offer.decorate.dtprevisao_entrega_plano %></span>
        </li>
      </ul>

    </div>

    <div class="col-md-offset-1 col-md-5 col-lg-offset-0 col-lg-6">

      <ul class="list-group">
        <li class="list-group-item list-group-item-success">
          Detalhes da grade
        </li>
        <li class="list-group-item">
          <%= modelGrid.human_attribute_name(:year) %>
          <span class="badge"><%= @offer.grid.year %></span>
        </li>

        <li class="list-group-item">
          <%= modelGrid.human_attribute_name(:carga_horaria) %>
          <span class="badge"><%= @offer.grid.carga_horaria || 'Sem informação' %></span>
        </li>

        <li class="list-group-item">
          <%= model.human_attribute_name(:course) %>
          <span class="badge"><%= "[#{@offer.grid.course.sigla}] #{@offer.grid.course.name}" %></span>
        </li>
      </ul>

    </div>

    <div class="col-md-offset-1 col-md-11 col-lg-offset-0 col-lg-12">

      <div class='table-responsive'>
        <table class='table table-striped table-bordered table-hover table-condensed'>
          <caption class="well-sm alert-success">Componentes curriculares ofertados</caption>
          <thead>
            <tr class="alert-warning">
              <th><%= modelGridDiscipline.human_attribute_name(:discipline_id) %></th>
              <th><%= modelGridDiscipline.human_attribute_name(:year) %></th>
              <th><%= modelGridDiscipline.human_attribute_name(:carga_horaria) %></th>
              <th><%= modelOfferDiscipline.human_attribute_name(:ead_percentual_maximo) %></th>
              <th>Professores</th>
              <th class="text-center" colspan="2"><%= t('helpers.actions') %></th>
            </tr>
          </thead>
          <tbody>
            <% @offer.offer_disciplines.each do |d| %>
              <% ultimo_plano_aprovado = ultimo_plano_aprovado_por_disciplina(d.id) %>
              <tr>
                <td style="width: 40%;"><%= "#{d.grid_discipline.discipline.sigla} - #{d.grid_discipline.discipline.title}" %></td>
                <td class="text-center"><%= d.grid_discipline.decorate.ano_semestre %></td>
                <td><%= "#{d.decorate.carga_horaria_hora_text} - #{d.decorate.carga_horaria_aula_text}" %></td>
                <td class="text-center"><%= "#{d.ead_percentual_maximo}" %></td>
                <td><%= d.decorate.professores %></td>
                <td><%= ultimo_plano_aprovado.decorate.link_pdf('btn-xs btn-block') unless ultimo_plano_aprovado.nil? %></td>
                <td class="text-center"><%= d.grid_discipline.decorate.link_show %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>

  </div>
</div>

<!-- <div class="page-header">
  <= link_to offers_path, class: 'btn btn-default' do %>
    <i class='fa fa-list fa-2'></i>
    <= t('helpers.links.back') %>
  < end %>
  <= link_to edit_offer_path(@offer), class: 'btn btn-primary' do %>
    <i class='fa fa-pencil-square-o fa-2'></i>
    <= t('helpers.links.edit') %>
  < end %>
  <h1>Show offer</h1>
</div>

<dl class="dl-horizontal">
  Year:
  <= @offer.year %>

  Semestre:
  <= @offer.semestre %>

  Type:
  <= @offer.type_offer %>

  Course:
  <= @offer.grid.course %>

</dl> -->